### ISSUE TITLE
Error: permission denied

### ISSUE THREAD

**Issue by OLEG-XEP** [alk3p/aosp-dtc#1]
When using these dtc scripts when compiling the kernel for OnePlus 8 Pro using Google Clang 11.0.3, at the very end an error appears:  
bin/sh: 1: /root/aosp-dtc: Permission denied.  
sudo and chmod don't help.  Please tell me what could be the problem.

**Comment by alk3pInjection** [comment]
Well, this is a set of scripts oriented for aosp-dtc's standalone compilation.
As to the handling of in-kernel dtc, @xzr467706992 has provided a practical solution on platform 4.19/kona.

> Reference: https://github.com/xzr467706992/android_kernel_oneplus_sm8250/commits/789060a

Another suggestion is, using prebuilt dtc might also be a feasible option.

This issue will be closed for now, but feel free to reopen it for any reason.
